services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=carDB'
      - 'POSTGRES_USER=carUser'
      - 'POSTGRES_PASSWORD=password'

    ports:
      - '5432:5432'

    labels:
      org.springframework.boot.jdbc.parameters: 'ssl=true&sslmode=require'